### PR TITLE
Update export to ESM syntax

### PR DESCRIPTION
**Pull request by zakjan**
Hi, so I have finally found the cause for https://github.com/graphology/graphology/pull/130#issuecomment-598131628

Actually after the recent Webpack update, also importing in browser is broken in 0.15.0 - 0.16.1. When you try to load build/graphology[.min].js with script tag into browser, it throws `Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'`.

The offending code is both ESM and CommonJS syntax in the same file https://github.com/graphology/graphology/blob/master/src/index.js#L82-L97. Webpack 3 didn't complained about this syntax. Webpack 4 started wrapping such file with https://github.com/webpack/webpack/blob/v4.42.0/buildin/harmony-module.js which causes `module.exports` to be readonly. Webpack 5 added a better error message about it which makes it very clear, please see https://github.com/webpack/webpack/pull/8748.

In this PR, I have updated the export to ESM syntax. The existing support for CommonJS import (`Graph.* = *` lines) is remained so that tests/instantiation.js passes. However I'd consider removing the lines later, in theory it should work without it.

### CODE REVIEW

**Comment by Yomguithereal** [comment]
> However I'd consider removing the lines later, in theory it should work without it.

The issue with this is that people relying on CommonJS, and more importantly Node.js, will have to require by appending `.default`, no? If so this solution is not viable.

**Comment by zakjan** [comment]
I understand, there might be another Webpack setting to make it behave in a better way, I don't know yet, but it seems weird to need to have both export syntaxes... :/

**Comment by Yomguithereal** [comment]
Yes, the whole ESM vs. commonJS conundrum is particularly bothersome and devilish :)

> but it seems weird to need to have both export syntaxes...

It is really not if you want anyone to be able to import the lib from any standard :)

**Comment by Yomguithereal** [comment]
This said, wasn't some key implemented in `package.json` to be able to specify different endpoints for ESM and commonjs?

**Comment by zakjan** [comment]
Yes, see one of my libs https://github.com/zakjan/leaflet-lasso/blob/master/package.json. `module` field is not official yet, here is some context I could find https://stackoverflow.com/a/47537198/1823988 (btw, I used Webpack in my lib as well, but then I switched to Rollup because it seems that Webpack is more suitable for full webapps, lightweight Rollup for libraries)

**Comment by Yomguithereal** [comment]
Personally I provide a built bundle for people still not using packages today and dropping scripts in their webpage the "old" way. I don't expect someone using modules to consume the library through build/graphology.min.js

**Comment by zakjan** [comment]
Right, that's the UMD target, no modules there at all.

**Comment by zakjan** [comment]
Closed in favor of https://github.com/graphology/graphology/pull/135

**Pull request closed without merging**
