### PR TITLE
Bundle can't be imported in non-browser environments since 0.15.0

### PR DESCRIPTION
**Pull request by zakjan**
Since 0.15.0, graphology bundle can't be imported to non-browser environments, because of reference to `window` in Webpack wrapper.

Specifically importing in WebWorker causes promise rejection with null message in Chrome 80, `ReferenceError: window is not defined` in Firefox 73.

```importScripts('https://unpkg.com/graphology@0.16.0/build/graphology.min.js');```

The same error can be also triggered by importing bundle in NodeJS, if someone would prefer it to usual import from dist directory.

0.14.1 worked flawlessly.

This error is caused by Webpack upgrade to 4 and can be fixed by `globalObject: 'this'` in Webpack config. See discussion at https://github.com/markdalgleish/static-site-generator-webpack-plugin/issues/130

### CODE REVIEW

**Comment by Yomguithereal** [comment]
Thanks @zakjan. I didn't know that webpack made such a daft change to the way they bundle. On a side note, where are you using the built bundle outside of the browser?

**Comment by zakjan** [comment]
Well, it was in WebWorker in browser, where window is not available. Maybe there is a better name for it.

**Comment by Yomguithereal** [comment]
Do you need a npm release?

**Comment by zakjan** [comment]
No rush, up to you.

**Comment by Yomguithereal** [comment]
v0.16.1 is up

**Comment by zakjan** [comment]
Hmm I'm getting another error, `TypeError: "exports" is read-only`. Investigating.

**Pull request merged**
