### PR TITLE
Fix graphology declaration file export

### PR DESCRIPTION
**Pull request by shahzod418**
Fixed this error:

> There are types at 'my-project/node_modules/graphology/dist/graphology.d.ts', but this result could not be resolved when respecting package.json "exports". The 'graphology' library may need to update its package.json or typings.

### CODE REVIEW

**Comment by Yomguithereal** [comment]
@shahzod418 is this backward-compatible with older TypeScript versions? Shouldn't we keep both the `types` root key as well as adding one within `exports`?

**Comment by Yomguithereal** [comment]
> Should I do it?

If it does not break anything to have both, yes I think we should do so as a precaution.

**Comment by shahzod418** [comment]
@Yomguithereal 
Done

**Comment by Yomguithereal** [comment]
Will merge and release thanks.

**Pull request merged**
